<?php

namespace BinaryStudioAcademy\Game\Commands\Handlers;


use BinaryStudioAcademy\Game\Contracts\Io\Writer;
use BinaryStudioAcademy\Game\Contracts\Storage;

class HelpHandler extends AbstractHandler
{
    private $commands;

    public function __constructor(Storage $storage, Writer $writer,array $commands)
    {
        $this->commands = $commands;
        parent::__constructor($storage, $writer); // TODO: Change the autogenerated stub
    }

    public function execute($data = null): void
    {
        $this->writer->writeln('Available commands:');
        foreach ($this->commands as $command)
        {
            $this->writer->writeln($command['command']);
        }
    }
}